common:
  containerRegistryURL: bestacr12345.azurecr.io/todo-ui
  ingressClass: azure-application-gateway
  
ui:
  replicas: 2
  image:
    name: todo-ui
    tag: v4
  port: 80
  ServicePort: 80
  ingress:
    host: dev-ui.vishal.shop


getTask:
  replicas: 
  image:
    name: todo-get-tasks-api  
    tag: v1
  port: 8000
  ServicePort: 80
  connectionString: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:vishalsqlserver123.database.windows.net,1433;Database=vishalsqldb;Uid=sqladminuser;Pwd=SqlAdmin@12345;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
  ingress:
    host: dev-get-tasks-api.jhandu.shop
    ingressClass: azure-application-gateway


deleteTask:
  replicas: 1
  image:
    name: todo-delete-tasks-api
    tag: v1
  port: 8000
  ServicePort: 80
  connectionString: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:vishalsqlserver123.database.windows.net,1433;Database=vishalsqldb;Uid=sqladminuser;Pwd=SqlAdmin@12345;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
  ingress:
    host: dev-delete-task-api.jhandu.shop
    ingressClass: azure-application-gateway


addTask:
  replicas: 1
  image:
    name: todo-add-tasks-api
    tag: v1
  port: 8000
  ServicePort: 80
  connectionString: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:vishalsqlserver123.database.windows.net,1433;Database=vishalsqldb;Uid=sqladminuser;Pwd=SqlAdmin@12345;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
  ingress:
    host: dev-add-task-api.jhandu.shop
    ingressClass: azure-application-gateway